import { Button } from "@/components/ui/button"
import { MessageCircle, ChevronUp } from "lucide-react"
import Image from "next/image"

export function GamingFooter() {
  return (
    <footer className="bg-black text-white relative">
      {/* Download App Section */}
      <div className="flex justify-center p-6">
        <Button className="bg-white text-black hover:bg-gray-100 rounded-full px-6 py-3 font-medium">
          DOWNLOAD APP
          <div className="flex items-center gap-2 ml-2 text-sm text-gray-600">
            <span>📱 Android</span>
            <span>🍎 iOS</span>
          </div>
        </Button>
      </div>

      {/* Tutorial Buttons */}
      <div className="flex flex-wrap justify-center gap-4 px-6 mb-8">
        {[
          "1. How to Login",
          "2. Introduction",
          "3. How to Withdraw",
          "4. How to Deposit English",
          "5. How to Deposit Hindi",
        ].map((text, index) => (
          <Button
            key={index}
            className="bg-teal-600 hover:bg-teal-700 text-white px-4 py-2 rounded-lg text-sm font-medium"
          >
            {text}
          </Button>
        ))}
      </div>

      {/* Main Footer Content */}
      <div className="px-6 pb-8 max-w-7xl mx-auto">
        <div className="flex flex-col lg:flex-row items-start gap-8">
          {/* Logo and Company Info */}
          <Image src={"/footer-logo.webp"} alt="footer-logo" width={150} height={150}/>

          {/* Legal Text */}
          <div className="flex-1 text-sm text-gray-300 leading-relaxed">
            LOTUS365 is a limited liability company incorporated under the laws of Curacao Players are requested not to
            contact any untrusted sources for LOTUS365 accounts as this is an online site and they can only register
            independently without any agents. Only deposit through the account details generated by the system or
            provided by our official support team.
          </div>
        </div>

        {/* Payment Methods */}
        <div className="mt-8 mb-8">
          <div className="flex flex-wrap items-center justify-center gap-6 opacity-60">
            {/* Payment method logos - using placeholder text for now */}
            {[
              "BANK DEPOSIT",
              "RUPEE-O",
              "UPI",
              "PhonePe",
              "Paytm",
              "IMPS",
              "FreeCharge",
              "G Pay",
              "Airtel",
              "AstroPay",
            ].map((method, index) => (
              <div key={index} className="text-gray-400 text-xs font-medium px-2 py-1 border border-gray-600 rounded">
                {method}
              </div>
            ))}
          </div>
        </div>

        {/* Social Media and Rules */}
        <div className="flex flex-col sm:flex-row justify-between items-center gap-4">
          {/* Social Media Icons */}
          <div className="flex items-center gap-4">
            <Button size="icon" className="bg-green-500 hover:bg-green-600 rounded-full w-10 h-10">
              <span className="text-white">📱</span>
            </Button>
            <Button size="icon" className="bg-red-600 hover:bg-red-700 rounded-full w-10 h-10">
              <span className="text-white">📺</span>
            </Button>
            <Button size="icon" className="bg-blue-500 hover:bg-blue-600 rounded-full w-10 h-10">
              <span className="text-white">✈️</span>
            </Button>
            <Button size="icon" className="bg-pink-500 hover:bg-pink-600 rounded-full w-10 h-10">
              <span className="text-white">📷</span>
            </Button>
          </div>

          {/* Rules Text */}
          <div className="text-gray-400 text-sm">Rules Regulations 2016-2025 v. 9.66</div>
        </div>
      </div>

      {/* Fixed Position Elements */}
      {/* Chat Support */}
      <Button
        size="icon"
        className="fixed bottom-6 left-6 bg-teal-600 hover:bg-teal-700 rounded-full w-14 h-14 shadow-lg"
      >
        <MessageCircle className="w-6 h-6" />
      </Button>

      {/* Scroll to Top */}
      <Button
        size="icon"
        className="fixed bottom-6 right-6 bg-teal-600 hover:bg-teal-700 rounded-full w-14 h-14 shadow-lg"
      >
        <ChevronUp className="w-6 h-6" />
      </Button>
    </footer>
  )
}
